### ISSUE TITLE
VM reserved instance recommendations show duplicates

### ISSUE THREAD

**Issue by StijnBerendse** [helderpinto/AzureOptimizationEngine#108]
In the PowerBI cost overview, when a reservation opportunity is found, it is currently shown six times: once for each combination of lookback period and duration. This cannot be filtered by taking only the minimum and maximum grouped by resource for example, because the resource ID is not available. In the example screenshot of the PowerBI cost overview, this problem is not present, even though the same recommendation is given ("Consider virtual machine reserved instance to save over your on-demand costs").

Is there a fix for this?

See image below for reference:
![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10389706/14dfc481-c561-4c88-bb1f-d6b60a30481e)

**Comment by StijnBerendse** [comment]
Another big difference between the example and my issue is that the instancename in my case is simply the subscription ID, whereas the example seems to show a truly unique instance/resource ID.

**Comment by helderpinto** [comment]
Hi @StijnBerendse! Thanks for creating this issue.

Those recommendations are coming from Azure Advisor, which has been providing 6 different entries per RI recommendation, as you correctly noticed. This was a change introduced earlier this year by the Azure Advisor team. I recognize the AOE reporting is misleading, but as it was built to present Advisor recommendations just as they are delivered by the Advisor API, there needs to be a work-around development specific to the RI recommendations, which are the only ones manifesting this problem.

There is backlog item to address this problem. Please, let this issue open. It will be closed automatically once the fix is published.

**Comment by StijnBerendse** [comment]
Ah, that is unfortunate, but thanks for the explanation! I've tried to find a workaround myself, but the problem I'm running into is that the recommendations no longer seem to be connected to the resources in any way. If I find a workaround, I'll update this thread.

**Comment by helderpinto** [comment]
This was fixed with a recent update to the `Recommendations` Workbook. The Workbook now presents only one Reservation recommendation per scope/SKU, using the largest savings opportunity as a reference.
