### ISSUE TITLE
Recommendation currencies are mixed

### ISSUE THREAD

**Issue by StijnBerendse** [helderpinto/AzureOptimizationEngine#112]
Hi,
A while back I mentioned an issue with duplicate recommendations that turned out to be caused by an Azure update, but I am wondering whether this update has also caused other problems such as mixed currencies.

To preface: our cost management is in EUR. The default "aesthetic" is in EUR too, as mentioned in this issue:https://github.com/helderpinto/AzureOptimizationEngine/issues/93. However, some recommendations in Azure Advisor are in USD. In that case, does the AOE account for that (by converting based on current exchange rate, for example), or does it simply (wrongly) assume the cost values to be in EUR too?

Thanks for replying!

**Comment by helderpinto** [comment]
Hi @StijnBerendse! Thank you for pointing this out. Unfortunately, AOE does not account for USD-only Advisor recommendations and wrongly presents those savings as being in the customer's contract currency. The only exception is the "Right-size or shutdown underutilized virtual machines" recommendation, for which savings are rated according to the customers' contract currency. This issue is going to be labeled as a proposed enhancement and will be closed once fixed. Definitely, Advisor recommendations are in need of more care in AOE. Thanks!

**Comment by StijnBerendse** [comment]
@helderpinto Thanks for the clarification. I noticed that there is a currency field attached to the recommendations. Is that currency correct and based on some kind of export? If that is reliable, I suppose that could be used for conversion purposes.

**Comment by helderpinto** [comment]
Yes, @StijnBerendse, the currency field that comes in the `AdditionalInfo` property is coming from Azure Advisor and is correct. The Recommendations Workbook could use this field to populate a new Currency column. That's what I am planning to do to address this limitation. Thanks for the suggestion.
