### ISSUE TITLE
SQL ingestion failing 

### ISSUE THREAD

**Issue by DevanshuSyk** [helderpinto/AzureOptimizationEngine#53]
Hello  the weekly SQL ingestion job starts failing after  first run 
Looks like the job is consuming all the 400 MB memory allocated to it .does a anyone has any work around ?

Job Name:Ingest-RecommendationsToSQLServer
Logs:The runbook job failed due to sandbox running out of memory. Each Azure Automation sandbox is allocated 400 MB of memory. The job was attempted 3 times before it was suspended. See some common ways to resolve this at https://aka.ms/AAMemoryLimit

**Comment by helderpinto** [comment]
@DevanshuSyk , this is probably due to the amount of recommendations that are being collected. There are two possible work-arounds:

- Implement an [Automation Hybrid Runbook Worker](https://docs.microsoft.com/en-us/azure/automation/automation-hybrid-runbook-worker), which allows you to have control on the amount of memory available for the job, and then reconfigure the SQL ingestion runbook to use the hybrid worker.
- Or filter out some high-volume recommendation types, such as Advisor Security, for example. To filter out Advisor Security recommendations, you can create an `AzureOptimization_AdvisorFilter` Automation variable and set it to the following: `HighAvailability,Performance,OperationalExcellence` (we are leaving out the Security category).

**Comment by DevanshuSyk** [comment]
Thankx @helderpinto  for quick response.I am closing the issue .If the filter doesn't work will implement a Hybrid Runbook worker.
