### ISSUE TITLE
The query on the Azure AD Roles does not return updated data

### ISSUE THREAD

**Issue by RobertMarq0408** [helderpinto/AzureOptimizationEngine#56]
We have tried to find out why it does not bring the updated information in the workbook: "(Identities and Roles)" of our tenant when we enable it for the first time, however, when detecting that there is no overflow in the database and that the Jobs in the Automation Account -> runbooks are executing correctly and we do not know why it is not updated.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/110930340/183727026-67b9a135-5364-421d-8652-1f135ef06a11.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/110930340/183727033-90543540-85ee-4458-b614-92962abfb2d1.png)

**Comment by helderpinto** [comment]
Can you please check the following:

- Is the `Export-RBACAssignmentsToBlobStorage` runbook running correctly? Can you share its output?
- In the Log Analytics workspace, run this query to check whether the user "Miguel" is being successfully ingested:

```
AzureOptimizationAADObjectsV1_CL
| where PrincipalNames_s contains 'miguel'
```

- If the query above returns the expected results, run the query below to validate the roles assigned to that user:

```
AzureOptimizationAADObjectsV1_CL
| where PrincipalNames_s contains 'miguel'
| join kind=inner (AzureOptimizationRBACAssignmentsV1_CL) on $left.ObjectId_g == $right.PrincipalId_g
| project PrincipalNames_s, ObjectId_g, RoleDefinition_s, Scope_s
```

If any of the queries above does not return results, please let me know, so that we troubleshoot further.

**Comment by RobertMarq0408** [comment]
Hello Helder Pinto -

Thank you very much for your response and follow-up on the case.

These are the evidences on our Azure Portal according to your request:

- Is the Export-RBACAssignmentsToBlobStorage runbook running correctly? Can you share its output?

<img width="1496" alt="Screen Shot 2022-08-12 at 14 16 55" src="https://user-images.githubusercontent.com/110930340/184429342-ec690d42-e85b-4a82-a9df-5e001bc20122.png">
<img width="1493" alt="Screen Shot 2022-08-12 at 14 18 03" src="https://user-images.githubusercontent.com/110930340/184429384-e3640c73-fe11-444a-970a-db3958963a36.png">
<img width="1491" alt="Screen Shot 2022-08-12 at 14 19 56" src="https://user-images.githubusercontent.com/110930340/184429430-f9c40128-b1fe-4587-9842-086248637f7b.png">

Below I share the evidence and results of the queries:

<img width="1680" alt="Screen Shot 2022-08-12 at 14 20 41" src="https://user-images.githubusercontent.com/110930340/184429474-1404265a-f2cf-406d-bfd9-71f18758a580.png">

but the second query did not return anything:

<img width="1677" alt="Screen Shot 2022-08-12 at 14 25 14" src="https://user-images.githubusercontent.com/110930340/184429497-3bb5daf8-3081-4554-920a-424589f7525c.png">


Although I understand that the time range at the end may be due to an issue, we would like to know if there is any consideration for the query results to be reflected, since we want to understand if it is a Workbook-side issue (runbooks, jobs , etc...) or is it an Azure AD issue?

I appreciate your time and patience while we sorted all this out.
 
Sincerely Roberto Marquez

**Comment by helderpinto** [comment]
Thank you for your patience @RobertMarq0408. The "Identities & Roles" Workbook is not showing all the ARM role assignments because the Managed Identity associated to the AOE Automation Account (`dashboardaoe-auto`) seems to have Reader privileges only on the `adm-prd` subscription. According to the AOE installation instructions, if you want AOE to look to your entire Azure landscape, you must assign the Reader role to `dashboardaoe-auto` in every subscription (or, better, Management Group) you want to include in the AOE scope. The day after you assign the role, you should be able to see all the data that has been missing.

**Comment by RobertMarq0408** [comment]
Hello again Helder Pinto -

Thank you very much for your response and follow-up on the case. I would like to briefly share with you the results obtained according to the adjustment in the assignment of the Roles: ***Reader*** in the root Management Group and letting us wait for the next day according to the change that we did yesterday, I share with you the evidence that the user already appears correctly in the Dashboard:

Resolution:

- The role of Lectura/Reader was added in the dashboardaeo-auto resource in the Management Group from the root, in which the change was taken until the next day, so it was as follows:

Evidence in the Raiz Management Group: mg-bineo

<img width="1157" alt="Screen Shot 2022-08-22 at 16 13 41" src="https://user-images.githubusercontent.com/110930340/186277351-a0a1ee55-646c-49ae-b004-a20dc923962c.png">


Access Control in [RBAC] – for the Dashboardaeo-auto assigned entity in the Management Group:

 
<img width="1161" alt="Screen Shot 2022-08-22 at 16 14 04" src="https://user-images.githubusercontent.com/110930340/186277119-47694e70-e12c-4f05-a3ec-65f854adff6a.png">


Therefore, the final evidence shows that we are already detecting user records and user assignments in the dashboardaoe-auto:

<img width="1680" alt="Screen Shot 2022-08-23 at 17 22 03" src="https://user-images.githubusercontent.com/110930340/186277384-b10ea453-eafe-44a2-b5ba-2a302a8de943.png">

Therefore I would like to thank you infinitely for the attention and support, how kind you have been.

Thank you very much
Cheers!
