### ISSUE TITLE
Doubt in logic of metrics exporting

### ISSUE THREAD

**Issue by rasselmaliyekkal** [helderpinto/AzureOptimizationEngine#74]
Hi Luke,

Correct me if am wrong, for metrics collection using az monitor command we have option to look back for max 30/90 days to analyse utilisation.
Then why we are exporting daily utilisation to log analytics workspace and analysing average utilisation using kql and variable (look back period).

**Comment by helderpinto** [comment]
Hi @rasselmaliyekkal. Metrics are being ingested into Log Analytics so that we can 1) easily correlate, with a single KQL query, metric data with other dimensions, such as cost and resource properties, and 2) easily present graphical evidence supporting the recommendation at the tip of a link to a KQL query.
