### ISSUE TITLE
Is it possible to use this tool as a MSP? GDAP Subscriptions customers

### ISSUE THREAD

**Issue by mvthul** [helderpinto/AzureOptimizationEngine#76]
Hi i was wondering if this Engine is possible for use multi tenancy.
We are a MSP and got all our customers in our Partner portal and rolling out GDAP at the moment.

This tool can be of good use if its possible to get all our tenants information in one.

Is it already possible to manage/view all tenants with this tool?

**Comment by mvthul** [comment]
Multi Azure enviroments

**Comment by helderpinto** [comment]
Thanks for raising this issue, @mvthul. It is possible to use multi-tenancy/multi-Azure-cloud in AOE, although it was not designed for MSP scenarios. It was thought for customers who have multiple tenants/clouds (e.g., multiple Azure ADs or Azure Global + Azure Gov/China). 

You will notice all data collection Runbooks accept as parameters Tenant ID (`externalTenantId`), Environment (`externalCloudEnvironment`) and Credential (`externalCredentialName`), which are never used in the default setup. Its usage is not documented nor automated, though. In a nutshell, you'd have to create one Automation Credential for each customer (client ID + secret) and add a new schedule for each runbook/customer using those parameters. However, most of the reports (Workbooks/Power BI) would have to be adapted in order to better segregate all the different customers, because you can only filter by Subscription (not by tenant) currently. Your contributions to improve multi-tenancy support are welcome ;-)
