### ISSUE TITLE
Unable to view Subscription names in the AzureOptimizationRecommendationsV1_CL LA table

### ISSUE THREAD

**Issue by arunjvai** [helderpinto/AzureOptimizationEngine#79]
I am not able to view Subscription names in the AzureOptimizationRecommendationsV1_CL LA table. All the other columns are being populated. This is an issue as the PowerBI report and the Workbooks only display the Subscription where the AzOptimization Engine has been installed. All the necessary access has been provided to view all subscriptions.

**Comment by helderpinto** [comment]
Please run the following query

```kql
AzureOptimizationResourceContainersV1_CL
| where TimeGenerated > ago(1d)
| where ContainerType_s == 'microsoft.resources/subscriptions'
| project SubscriptionGuid_g, ContainerName_s
```

The table above is fed by the `Export-ARGResourceContainersPropertiesToBlobStorage` runbook and is where recommendations get subscription names from. If the table does not show results, then this may be a hint to the cause.

**Comment by arunjvai** [comment]
> Please run the following query
> 
> ```kusto
> AzureOptimizationResourceContainersV1_CL
> | where TimeGenerated > ago(1d)
> | where ContainerType_s == 'microsoft.resources/subscriptions'
> | project SubscriptionGuid_g, ContainerName_s
> ```
> 
> The table above is fed by the `Export-ARGResourceContainersPropertiesToBlobStorage` runbook and is where recommendations get subscription names from. If the table does not show results, then this may be a hint to the cause.

This was not showing the list of subs earlier, but it started to show after I executed the runbook.

Now on checking this in  the SQL Database I see subscription ID's but not the Subscription names. Is there a way to trigger the update so this data is populated. ? 

The Original issue that I am facing is that the PBI dashboard has certain views that have Subscription as a filter. This filter currently shows only the one where I had AOE installed.

**Comment by helderpinto** [comment]
The `Export-ARGResourceContainersPropertiesToBlobStorage` should have run, as it is normally scheduled to run daily. Have you changed or removed the default schedules? In order to have complete recommendations with the subscription name, you have to wait for the weekly recommendations generation schedule. You can speed it up, but you must know the order in which all the jobs run.

To widen the scope of subscriptions covered by AOE, please read the [usage instructions](https://github.com/helderpinto/AzureOptimizationEngine#widening-the-scope-of-aoe-recommendations---more-subscriptions-or-more-workspaces).

**Comment by arunjvai** [comment]
This is working and can be closed. Thanks !
